pipelines:
  default:
    - step:
        name: Build
        image: maven:3.3.9
        caches:
          - maven
        script:
          - mvn -B verify
  tags:
    '*':
    - step:
        name: Build
        image: maven:3.3.9
        caches:
          - maven
        script:
          - mvn -B verify
    - step:
        name: Containerize
        services:
          - docker
        caches:
          - docker
        script:
          - export IMAGE_NAME=${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}:$BITBUCKET_TAG
          - docker build -t $IMAGE_NAME .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME