version: '3.4'
volumes:
  storage:
  db:
services:
  mcontent:
    image: nolwenture/mcontent
    build: .
    environment:
      - APP_HOST
      - APP_PORT
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASS
      - MYSQL_DATABASE
      - SMS_HOST
      - SMS_PORT
      - SMS_USER
      - SMS_PASS
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_SECURE
      - EMAIL_USER
      - EMAIL_PASS
      - EMAIL_FROM
      - EMAIL_ADMINS
      - CONTENT_URL
      - DISCOVERY_URL
    ports:
      - 8080:8080
    volumes:
      - storage:/storage
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Asdf!234
      - MYSQL_USER
      - MYSQL_PASS
      - MYSQL_DATABASE
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql