package com.mnewservice.mcontent.web;

import com.mnewservice.mcontent.domain.*;
import com.mnewservice.mcontent.manager.AbstractDeliverableManager;
import com.mnewservice.mcontent.manager.DeliveryPipeManager;
import com.mnewservice.mcontent.manager.FileManager;
import com.mnewservice.mcontent.manager.NotificationManager;
import com.mnewservice.mcontent.manager.ProviderManager;
import com.mnewservice.mcontent.manager.ScheduledDeliverableManager;
import com.mnewservice.mcontent.manager.SeriesDeliverableManager;
import com.mnewservice.mcontent.manager.ServiceManager;
import com.mnewservice.mcontent.manager.UserManager;
import com.mnewservice.mcontent.repository.entity.AbstractDeliverableEntity;
import com.mnewservice.mcontent.repository.entity.CustomContentEntity;
import com.mnewservice.mcontent.repository.entity.FileEntity;
import java.io.InputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.stream.Collectors;
import javax.servlet.http.Part;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.validation.ObjectError;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class ContentController {

    private static final Logger LOG
            = Logger.getLogger(ContentController.class);

    @Value("${application.notification.deliverable.created.message.subject}")
    private String deliverableCreatedMessageSubject;

    @Value("${application.notification.deliverable.created.message.text}")
    private String deliverableCreatedMessageText;

    @Value("${application.notification.deliverable.approved.message.subject}")
    private String deliverableApprovedMessageSubject;

    @Value("${application.notification.deliverable.approved.message.text}")
    private String deliverableApprovedMessageText;

    @Value("${application.notification.deliverable.disapproved.message.subject}")
    private String deliverableDisapprovedMessageSubject;

    @Value("${application.notification.deliverable.disapproved.message.text}")
    private String deliverableDisapprovedMessageText;

    @Value("${application.content.themes}")
    private String themes;

    @Value("${application.content.themes.autogenerated}")
    private String autogeratedthemes;

    @Autowired
    private DeliveryPipeManager deliveryPipeManager;

    @Autowired
    private AbstractDeliverableManager deliverableManager;

    @Autowired
    private SeriesDeliverableManager seriesManager;

    @Autowired
    private ScheduledDeliverableManager scheduledManager;

    @Autowired
    private UserManager userManager;

    @Autowired
    private ServiceManager serviceManager;

    @Autowired
    private FileManager fileManager;

    @Autowired
    private ProviderManager providerManager;

    @Autowired
    private NotificationManager notificationManager;

    private boolean isAutogeneratedTheme(String theme) {
        return Arrays.asList(autogeratedthemes.split(",")).stream().map(s -> s.trim()).collect(Collectors.toList()).contains(theme);
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @ModelAttribute("allDeliverableTypes")
    public List<DeliverableType> populateDeliverableTypes() {
        return Arrays.asList(DeliverableType.values());
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @ModelAttribute("allThemes")
    public List<String> populateThemes() {
        return Arrays.asList(themes.split(",")).stream().map(s -> s.trim()).collect(Collectors.toList());
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @ModelAttribute("allDeliveryPipes")
    public List<DeliveryPipe> populateServices() {
       return deliveryPipeManager.getAllDeliveryPipes()
               .stream().collect(Collectors.toList());
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @ModelAttribute("allProviders")
    public List<User> populateProviders() {
        return userManager.getAllUsersByRoleName(Role.PROVIDER_SHOULD_BE_ENUM)
                .stream().collect(Collectors.toList());
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping({"/content/list"})
    public String listServices() {
        return "deliveryPipeList";
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping({"/deliverypipe/list/filtered/"})
    public ModelAndView listFilteredServices(@RequestParam(value = "nameFilter") String fname) {
        ModelAndView mav = new ModelAndView("deliveryPipeList");
        mav.addObject("filteredDeliveryPipes", deliveryPipeManager.getDeliveryPipes(fname)
                .stream().collect(Collectors.toList()));
        mav.addObject("nameFilter", fname);
        return mav;
    }

//<editor-fold defaultstate="collapsed" desc="error handling">
    @ResponseStatus(value = HttpStatus.CONFLICT, reason = "Data handling error")  // 409
    private class DataHandlingException extends RuntimeException {

        public DataHandlingException() {
            super();
        }

        public DataHandlingException(String s) {
            super(s);
        }

        public DataHandlingException(String s, Throwable throwable) {
            super(s, throwable);
        }

        public DataHandlingException(Throwable throwable) {
            super(throwable);
        }
    }

    private ModelAndView mavAddNLogErrorText(ModelAndView mav, List<ObjectError> errors) {
        String errorText = "";
        errors.stream().forEach((error) -> {
            errorText.concat(error.toString());
        });
        LOG.error(errorText);
        mav.addObject("errortext", errorText);
        return mav;
    }

//</editor-fold>
    //
//<editor-fold defaultstate="collapsed" desc="Delivery pipe">
    @PreAuthorize("hasAuthority('ADMIN')")
    @RequestMapping({"/deliverypipe/create"})
    public ModelAndView viewDeliveryPipe() {
        LOG.info("/deliverypipe/create");
        ModelAndView mav = new ModelAndView("deliveryPipeDetail");
        mav.addObject("deliveryPipe", new DeliveryPipe());
        return mav;
    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @RequestMapping({"/deliverypipe/{pipeId}"})
    public ModelAndView viewDeliveryPipe(@PathVariable("pipeId") long id) {
        LOG.info("/deliverypipe/" + id);
        ModelAndView mav = new ModelAndView("deliveryPipeDetail");
        mav.addObject("deliveryPipe", deliveryPipeManager.getDeliveryPipe(id));
        return mav;
    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @RequestMapping(value = {"/deliverypipe/{pipeId}"}, params = {"save"})
    public ModelAndView saveDeliveryPipe(
            @PathVariable("pipeId") String id,
            final DeliveryPipe deliveryPipe,
            final BindingResult bindingResult,
            final ModelMap model) {
        LOG.info("/deliverypipe/" + id + " param=save");
        ModelAndView mav = new ModelAndView("deliveryPipeDetail");

        if (bindingResult.hasErrors()) {
            mav = mavAddNLogErrorText(mav, bindingResult.getAllErrors());
            mav.addObject("deliveryPipe", model.getOrDefault("deliveryPipe", new DeliveryPipe()));
            mav.addObject("error", true);
        } else {
            try {
                // persist the object "service"
                DeliveryPipe savedDeliveryPipe = deliveryPipeManager.saveDeliveryPipe(deliveryPipe);
                mav.addObject("service", savedDeliveryPipe);
                mav.addObject("saved", true);
            } catch (Exception ex) {
                LOG.error(ex);
                throw new DataHandlingException(ex);
            }
        }

        return mav;
    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @RequestMapping({"/deliverypipe/remove/{pipeId}"})
    public ModelAndView viewRemovableDeliveryPipe(@PathVariable("pipeId") long id) {
        LOG.info("/deliverypipe/remove/" + id);
        ModelAndView mav = new ModelAndView("deliveryPipeRemove");
        DeliveryPipe pipe = deliveryPipeManager.getDeliveryPipe(id);
        mav.addObject("deliveryPipe", pipe);
        if (deliveryPipeManager.hasContent(id)) {
            mav.addObject("hasContent", "true");
        }
        if (serviceManager.getAllServicesByDeliveryPipe(id).size() > 0) {
            mav.addObject("error", "true");
            mav.addObject("errortext", "Service(s) uses delivery pipe. Can't remove. Remove service(s) first.");
        }
        return mav;
    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @RequestMapping(value = {"/deliverypipe/remove/{pipeId}"}, params = {"remove"})
    public ModelAndView removeDeliveryPipe(
            @PathVariable("pipeId") String id,
            final DeliveryPipe deliveryPipe,
            final BindingResult bindingResult,
            final ModelMap model) {
        LOG.info("/deliverypipe/remove/" + id + " param=remove");
        ModelAndView mav = new ModelAndView("deliveryPipeRemove");

        if (bindingResult.hasErrors()) {
            mav = mavAddNLogErrorText(mav, bindingResult.getAllErrors());
            mav.addObject("deliveryPipe", model.getOrDefault("deliveryPipe", new DeliveryPipe()));
            mav.addObject("error", true);
        }  else {
            try {
                deliveryPipeManager.removeDeliveryPipe(deliveryPipe.getId());
                deliveryPipe.setProviders(null);
                mav.addObject("deliveryPipe", deliveryPipe);
                mav.addObject("removed", true);
            } catch (Exception ex) {
                LOG.error(ex);
                throw new DataHandlingException(ex);
            }
        }

        return mav;
    }

//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Content list">
    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping({"/deliverypipe/{pipeId}/content/list"})
    public ModelAndView viewDeliveryPipeContent(@PathVariable("pipeId") long id) {
        LOG.info("/deliverypipe/" + id + "/content/list");
        ModelAndView mav;
        DeliveryPipe pipe = deliveryPipeManager.getDeliveryPipe(id);
        switch (pipe.getDeliverableType()) {
            case SCHEDULED:
                mav = new ModelAndView("deliveryPipeScheduledContent");
                mav.addObject("contents", //Thyme leaf javascript support is well unknown, so we do some magic here
                        scheduledManager.getDeliveryPipeScheduledDeliverable(id).stream().map(
                                deliverable -> new HashMap<String, Object>() {
                                    {
                                        put("id", deliverable.getId());
                                        put("title", deliverable.getContent().getTitle());
                                        put("status", deliverable.getStatus());
                                        put("date", new SimpleDateFormat("yyyy-MM-dd").format(deliverable.getDeliveryDate()));
                                        put("myStatus", deliverable.getStatus().toString().toLowerCase());
                                    }
                                }
                        ).collect(Collectors.toList()));
                break;

            case SERIES:
                mav = new ModelAndView("deliveryPipeSeriesContent");
                mav.addObject("contents", seriesManager.getDeliveryPipeSeriesDeliverable(id));
                break;

            default:
                throw new UnsupportedOperationException("Support for viewing content for pipe of type " + pipe.getDeliverableType() + " not implemented.");
        }
        mav.addObject(
                "deliveryPipe", pipe);
        return mav;
    }
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="getters">
    private DeliveryPipe getDeliveryPipe(long deliveryPipeId) throws Exception {
        DeliveryPipe deliveryPipe = deliveryPipeManager.getDeliveryPipe(deliveryPipeId);
        if (deliveryPipe == null) {
            throw new IllegalArgumentException(
                    "delivery pipe was not found with id=" + deliveryPipeId);
        }
        return deliveryPipe;
    }

    private SeriesDeliverable getSeriesDeliverable(long deliverableId,
                                                   DeliverableStatus disallowedStatus) throws Exception {
        SeriesDeliverable deliverable = seriesManager.getSeriesDeliverable(deliverableId);
        if (deliverable == null) {
            throw new IllegalArgumentException(
                    "series deliverable was not found with id=" + deliverableId);
        }
        if (disallowedStatus.equals(deliverable.getStatus())) {
            throw new IllegalStateException(
                    "series deliverable is on the wrong state : " + disallowedStatus.toString());
        }
        return deliverable;
    }

    private ScheduledDeliverable getScheduledDeliverable(long deliverableId,
                                                         DeliverableStatus disallowedStatus) {
        ScheduledDeliverable deliverable = scheduledManager.getScheduledDeliverable(deliverableId);
        if (deliverable == null) {
            throw new IllegalArgumentException(
                    "scheduled deliverable was not found with id=" + deliverableId);
        }
        if (disallowedStatus.equals(deliverable.getStatus())) {
            throw new IllegalStateException(
                    "scheduled deliverable is on the wrong state : " + disallowedStatus.toString());
        }
        return deliverable;
    }
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Series deliverable">
    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping(value = {"/deliverypipe/{deliveryPipeId}/series/create"})
    public ModelAndView createSeriesContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId) {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/series/create");
        ModelAndView mav = new ModelAndView("contentCreate");
        SeriesDeliverable newDeliverable = new SeriesDeliverable();
        newDeliverable.setStatus(DeliverableStatus.PENDING_APPROVAL);
        newDeliverable.setDeliveryDaysAfterSubscription(
                seriesManager.getNextDeliveryDay(deliveryPipeId));

        DeliveryPipe deliveryPipe = deliveryPipeManager.getDeliveryPipe(deliveryPipeId);
        mav.addObject("autoGenerateContent", isAutogeneratedTheme(deliveryPipe.getTheme()));
        mav.addObject("deliveryPipe", deliveryPipe);
        mav.addObject(
                "deliverable",
                newDeliverable
        );
        return mav;
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping({"/deliverypipe/{deliveryPipeId}/series/{deliverableId}"})
    public ModelAndView viewSeriesContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId) {

        LOG.info("/deliverypipe/" + deliveryPipeId + "/series/" + deliverableId);

        DeliveryPipe deliveryPipe = deliveryPipeManager.getDeliveryPipe(deliveryPipeId);
        SeriesDeliverable deliverable = seriesManager.getSeriesDeliverable(deliverableId);

        ModelAndView mav = new ModelAndView(deliverable.getStatus() == DeliverableStatus.APPROVED ? "contentView" : "contentEdit");
        mav.addObject("autoGenerateContent", isAutogeneratedTheme(deliveryPipe.getTheme()));
        mav.addObject("deliveryPipe", deliveryPipe);
        mav.addObject("deliverable", deliverable);

        return mav;
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping(value = {"/deliverypipe/{deliveryPipeId}/series/{deliverableId}"}, params = {"save"})
    public ModelAndView saveSeriesContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId,
            final SeriesDeliverable deliverable,
            final BindingResult bindingResult,
            final ModelMap model) {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/series/" + deliverableId + " param=save");
        ModelAndView mav = new ModelAndView("contentEdit");

        if (bindingResult.hasErrors()) {
            mav = mavAddNLogErrorText(mav, bindingResult.getAllErrors());
            mav.addObject("deliverable", model.getOrDefault("deliverable", new SeriesDeliverable()));
            mav.addObject("error", true);
        } else {
            try {
                DeliveryPipe deliveryPipe = getDeliveryPipe(deliveryPipeId);
                // Save
                SeriesDeliverable savedContent = seriesManager.saveSeriesDeliverable(deliveryPipeId, deliverable);

                mav.addObject("autoGenerateContent", isAutogeneratedTheme(deliveryPipe.getTheme()));
                mav.addObject("deliveryPipe", deliveryPipe);
                mav.addObject("deliverable", savedContent);
                mav.addObject("saved", true);
                if (deliverable.getId() == null) {
                    contentCreationNotification(savedContent, deliveryPipe);
                }

            } catch (Exception ex) {
                LOG.error(ex);
                throw new DataHandlingException(ex);
            }
        }

        return mav;
    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @RequestMapping({"/deliverypipe/{deliveryPipeId}/series/{deliverableId}/approve"})
    @ResponseStatus(value = HttpStatus.OK)
    public void approveSeriesContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId) throws Exception {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/series/" + deliverableId + "/approve");
        SeriesDeliverable content = getSeriesDeliverable(deliverableId, DeliverableStatus.APPROVED);
        DeliveryPipe deliveryPipe = getDeliveryPipe(deliveryPipeId);

        content.setStatus(DeliverableStatus.APPROVED);
        seriesManager.saveSeriesDeliverable(deliveryPipeId, content);

        contentApproveNotification(content, deliveryPipe);
    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @RequestMapping({"/deliverypipe/{deliveryPipeId}/series/{deliverableId}/disapprove"})
    @ResponseStatus(value = HttpStatus.OK)
    public void disapproveSeriesContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId) throws Exception {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/series/" + deliverableId + "/disapprove");
        SeriesDeliverable content
                = getSeriesDeliverable(deliverableId, DeliverableStatus.PENDING_APPROVAL);
        DeliveryPipe deliveryPipe = getDeliveryPipe(deliveryPipeId);

        content.setStatus(DeliverableStatus.DISAPPROVED);
        seriesManager.saveSeriesDeliverable(deliveryPipeId, content);

        contentDisapproveNotification(content, deliveryPipe);
    }

    @PreAuthorize("hasAnyAuthority('ADMIN')")
    @RequestMapping({"/deliverypipe/{deliveryPipeId}/series/remove/{deliverableId}"})
    public ModelAndView viewRemovableSeriesContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId) {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/series/remove/" + deliverableId);
        SeriesDeliverable deliverable = seriesManager.getSeriesDeliverable(deliverableId);
        ModelAndView mav = new ModelAndView("contentSeriesRemove");
        mav.addObject("deliverable", deliverable);
        return mav;
    }

    @PreAuthorize("hasAnyAuthority('ADMIN')")
    @RequestMapping(value = {"/deliverypipe/{deliveryPipeId}/series/remove/{deliverableId}"}, params = {"remove"})
    public ModelAndView removeSeriesContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId,
            final SeriesDeliverable deliverable,
            final BindingResult bindingResult,
            final ModelMap model) {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/series/remove/" + deliverableId + " param=remove");
        ModelAndView mav = new ModelAndView("contentSeriesRemove");
        if (bindingResult.hasErrors()) {
            mav = mavAddNLogErrorText(mav, bindingResult.getAllErrors());
            mav.addObject("deliverable", model.getOrDefault("deliverable", new SeriesDeliverable()));
            mav.addObject("error", true);
        } else {
            try {
                seriesManager.removeSeriesDeliverable(deliverable.getId());
                mav.addObject("deliverable", deliverable);
                mav.addObject("removed", true);
            } catch (Exception ex) {
                LOG.error(ex);
                throw new DataHandlingException(ex);
            }
        }

        return mav;
    }

//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Scheduled deliverable">
    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping(value = {"/deliverypipe/{deliveryPipeId}/scheduled/create"}, params = {"date"})
    public ModelAndView createScheduledContent(@PathVariable("deliveryPipeId") long deliveryPipeId, @RequestParam(value = "date") String date) {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/scheduled/create param=date " + date);
        ModelAndView mav = new ModelAndView("contentCreate");
        ScheduledDeliverable newDeliverable = new ScheduledDeliverable();
        try {
            newDeliverable.setDeliveryDate(new SimpleDateFormat("yyyy-MM-dd").parse(date));
        } catch (ParseException ex) {
            LOG.error("Failed to parse date " + date, ex);
        }

        DeliveryPipe deliveryPipe = deliveryPipeManager.getDeliveryPipe(deliveryPipeId);
        mav.addObject("autoGenerateContent", isAutogeneratedTheme(deliveryPipe.getTheme()));
        mav.addObject("deliveryPipe", deliveryPipe);
        mav.addObject("deliverable", newDeliverable);
        return mav;
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping({"/deliverypipe/{deliveryPipeId}/scheduled/{deliverableId}"})
    public ModelAndView viewScheduledContent(@PathVariable("deliveryPipeId") long deliveryPipeId, @PathVariable("deliverableId") long deliverableId) {

        LOG.info("/deliverypipe/" + deliveryPipeId + "/scheduled/" + deliverableId);

        DeliveryPipe deliveryPipe = deliveryPipeManager.getDeliveryPipe(deliveryPipeId);
        ScheduledDeliverable deliverable = scheduledManager.getScheduledDeliverable(deliverableId);

        ModelAndView mav = new ModelAndView(deliverable.getStatus() == DeliverableStatus.APPROVED ? "contentView" : "contentEdit");
        mav.addObject("autoGenerateContent", isAutogeneratedTheme(deliveryPipe.getTheme()));
        mav.addObject("deliveryPipe", deliveryPipe);
        mav.addObject("deliverable", deliverable);
        return mav;
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping(value = {"/deliverypipe/{deliveryPipeId}/scheduled/{deliverableId}"}, params = {"save"})
    public ModelAndView saveScheduledContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId,
            final ScheduledDeliverable deliverable,
            final BindingResult bindingResult,
            final ModelMap model) {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/scheduled/" + deliverableId + " param=save");
        ModelAndView mav = new ModelAndView("contentEdit");

        if (bindingResult.hasErrors()) {
            mav = mavAddNLogErrorText(mav, bindingResult.getAllErrors());
            mav.addObject(
                    "deliverable",
                    model.getOrDefault("deliverable", new ScheduledDeliverable())
            );
            mav.addObject("error", true);
        } else {
            try {
                DeliveryPipe deliveryPipe = getDeliveryPipe(deliveryPipeId);
                if (deliverableId != 0) { // deliverableId == 0 when deliverable is in create state
                    deliverable.setFiles((List<ContentFile>) deliverableManager.getDeliverablesContentFiles(deliverableId));
                }
                ScheduledDeliverable savedContent = scheduledManager.saveScheduledDeliverable(deliveryPipeId, deliverable);
                mav.addObject("autoGenerateContent", isAutogeneratedTheme(deliveryPipe.getTheme()));
                mav.addObject("deliveryPipe", deliveryPipe);
                mav.addObject("deliverable", savedContent);
                mav.addObject("saved", true);

                if (deliverable.getId() == null) {
                    contentCreationNotification(savedContent, deliveryPipe);
                }

            } catch (Exception ex) {
                LOG.error(ex);
                throw new DataHandlingException(ex);
            }
        }

        return mav;
    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @RequestMapping({"/deliverypipe/{deliveryPipeId}/scheduled/{deliverableId}/approve"})
    @ResponseStatus(value = HttpStatus.OK)
    public void approveScheduledContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId) throws Exception {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/scheduled/" + deliverableId + "/approve");
        ScheduledDeliverable content = getScheduledDeliverable(deliverableId, DeliverableStatus.APPROVED);
        DeliveryPipe deliveryPipe = getDeliveryPipe(deliveryPipeId);

        content.setStatus(DeliverableStatus.APPROVED);
        scheduledManager.saveScheduledDeliverable(deliveryPipeId, content);

        contentApproveNotification(content, deliveryPipe);
    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @RequestMapping({"/deliverypipe/{deliveryPipeId}/scheduled/{deliverableId}/disapprove"})
    @ResponseStatus(value = HttpStatus.OK)
    public void disapproveScheduledContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId) throws Exception {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/scheduled/" + deliverableId + "/disapprove");
        ScheduledDeliverable content = getScheduledDeliverable(deliverableId, DeliverableStatus.PENDING_APPROVAL);
        DeliveryPipe deliveryPipe = getDeliveryPipe(deliveryPipeId);

        content.setStatus(DeliverableStatus.DISAPPROVED);
        scheduledManager.saveScheduledDeliverable(deliveryPipeId, content);

        contentDisapproveNotification(content, deliveryPipe);
    }

    @PreAuthorize("hasAnyAuthority('ADMIN')")
    @RequestMapping({"/deliverypipe/{deliveryPipeId}/scheduled/remove/{deliverableId}"})
    public ModelAndView viewRemovableScheduledContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId) {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/scheduled/remove/" + deliverableId);
        ScheduledDeliverable deliverable = scheduledManager.getScheduledDeliverable(deliverableId);
        ModelAndView mav = new ModelAndView("contentScheduledRemove");
        mav.addObject("deliverable", deliverable);
        return mav;
    }

    @PreAuthorize("hasAnyAuthority('ADMIN')")
    @RequestMapping(value = {"/deliverypipe/{deliveryPipeId}/scheduled/remove/{deliverableId}"}, params = {"remove"})
    public ModelAndView removeScheduledContent(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableId") long deliverableId,
            final ScheduledDeliverable deliverable,
            final BindingResult bindingResult,
            final ModelMap model) {
        LOG.info("/deliverypipe/" + deliveryPipeId + "/scheduled/remove/" + deliverableId + " param=remove");
        ModelAndView mav = new ModelAndView("contentScheduledRemove");
        if (bindingResult.hasErrors()) {
            mav = mavAddNLogErrorText(mav, bindingResult.getAllErrors());
            mav.addObject("deliverable", model.getOrDefault("deliverable", new ScheduledDeliverable()));
            mav.addObject("error", true);
        } else {
            try {
                scheduledManager.removeScheduledDeliverable(deliverable.getId());
                mav.addObject("deliverable", deliverable);
                mav.addObject("removed", true);
            } catch (Exception ex) {
                LOG.error(ex);
                throw new DataHandlingException(ex);
            }
        }

        return mav;
    }

    //</editor-fold>

//<editor-fold defaultstate="collapsed" desc="notifications">
    private void contentCreationNotification(AbstractDeliverable deliverable,
            DeliveryPipe deliveryPipe) {
        String notificationSubject = String.format(
                deliverableCreatedMessageSubject,
                deliverable.getContent().getTitle());
        String notificationMessage = String.format(
                deliverableCreatedMessageText,
                deliverable.getContent().getTitle(),
                deliveryPipe.getName());

        notificationManager.notifyAdmin(notificationSubject, notificationMessage);
    }

    private void contentApproveNotification(
            AbstractDeliverable deliverable, DeliveryPipe deliveryPipe) {
        String notificationSubject = String.format(
                deliverableApprovedMessageSubject,
                deliverable.getContent().getTitle());
        String notificationMessage = String.format(
                deliverableApprovedMessageText,
                deliverable.getContent().getTitle(),
                deliveryPipe.getName());

        notify(deliveryPipe.getProviders(), notificationSubject, notificationMessage);
    }

    private void contentDisapproveNotification(
            AbstractDeliverable deliverable, DeliveryPipe deliveryPipe) {
        String notificationSubject = String.format(
                deliverableDisapprovedMessageSubject,
                deliverable.getContent().getTitle());
        String notificationMessage = String.format(
                deliverableDisapprovedMessageText,
                deliverable.getContent().getTitle(),
                deliveryPipe.getName());

        notify(deliveryPipe.getProviders(), notificationSubject, notificationMessage);
    }

    private void notify(Collection<User> users, String notificationSubject,
            String notificationMessage) {
        Collection<Provider> providers = new ArrayList<>();
        for (User user : users) {
            Provider provider = providerManager.findByUserId(user.getId());
            if (provider != null) {
                providers.add(provider);
            }
        }

        notificationManager.notifyProviders(
                providers, notificationSubject, notificationMessage);
    }
    //</editor-fold>

//<editor-fold defaultstate="collapsed" desc="File upload/remove">
//<editor-fold defaultstate="collapsed" desc="MyResponse">
    protected class MyResponse {

        private String message;
        private String error;
        private String data;
        private List<ContentFile> files;

//<editor-fold defaultstate="collapsed" desc="getter/setter">
        public MyResponse() {
            this.files = new ArrayList<>();
        }

        public String getMessage() {
            return message;
        }

        public void setMessage(String message) {
            this.message = message;
        }

        public String getData() {
            return data;
        }

        public void setData(String data) {
            this.data = data;
        }

        public List<ContentFile> getFiles() {
            return files;
        }

        public void setFiles(List<ContentFile> files) {
            this.files = files;
        }

        public String getError() {
            return error;
        }

        public void setError(String error) {
            this.error = error;
        }
//</editor-fold>
    }
//</editor-fold>

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping(value = {"/fileupload"})
    public @ResponseBody
    ResponseEntity<MyResponse> uploadDeliverableFile(
            MultipartHttpServletRequest request
    ) {
        LOG.info("file upload - " + request.getContextPath() + "/fileupload");
        MyResponse response = new MyResponse();

        try {
            Iterator<String> itr = request.getFileNames();

            while (itr.hasNext()) {
                String uploadedFile = itr.next();
                MultipartFile file = request.getFile(uploadedFile);
                LOG.info("Processing downloaded file: " + file.getContentType() + "(" + file.getOriginalFilename() + ")");

                ContentFile contentFile = new ContentFile();
                contentFile.setMimeType(file.getContentType());
                contentFile.setOriginalFilename(file.getOriginalFilename());
                LOG.info("Creating thumbnail image");
                contentFile.setThumbImage(ContentFile.generateThumbImage(file.getBytes()));

                // SMB and DB save
                contentFile = fileManager.saveFile(contentFile, file.getBytes());
                contentFile.createAndSetImageHtmlBlock();
                response.getFiles().add(contentFile);

            }
        } catch (Exception e) {
            LOG.error("File upload failed", e);
            response.setMessage("Error on handling request");
            response.setError(response.getMessage());
            return new ResponseEntity<>(response, HttpStatus.INTERNAL_SERVER_ERROR);
        }

        if (response.getFiles().stream().anyMatch(x -> {
            if (x.isAccepted()) {
                return false;
            }
            LOG.error("Request completed with errors. " + x.getErrorMessage());
            response.setMessage("Request completed with errors");
            response.setError(x.getErrorMessage());
            return true;
        })) {
            return new ResponseEntity<>(response, HttpStatus.INTERNAL_SERVER_ERROR);
        }

        LOG.info("File upload completed");
        response.setMessage("Request completed");
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping(value = {"/deliverypipe/{deliveryPipeId}/{deliverableType}/{deliverableId}/files"})
    public @ResponseBody
    ResponseEntity<MyResponse> saveDeliverableFile(
            @PathVariable("deliveryPipeId") long deliveryPipeId,
            @PathVariable("deliverableType") String deliverableType,
            @PathVariable("deliverableId") long deliverableId,
            MultipartHttpServletRequest request
    ) {
        LOG.info("file save - " + request.getContextPath() + "/deliverypipe/" + deliveryPipeId + "/" + deliverableType + "/" + deliverableId + "/files");
        MyResponse response = new MyResponse();

        try {
            AbstractDeliverableEntity entity = deliverableManager.findOne(deliverableId);
            if (entity == null) {
                String errMsg = "Can't find deliverable from repository with id=" + deliverableId;
                LOG.error(errMsg);
                throw new Exception("Internal error - " + errMsg);
            }

            Collection<Part> parts = request.getParts();
            String fileUuid;
            for (Part part : parts) {
                String partName = part.getName();
                InputStream dataStream = part.getInputStream();
                fileUuid = "";
                if (dataStream != null) {
                    byte[] buff = new byte[(int) part.getSize()];
                    int b, i = 0;
                    while ((b = dataStream.read()) != -1) {
                        buff[i++] = (byte) b;
                    }
                    fileUuid = new String(buff, "UTF-8");
                }

                if (partName.equals("addFile")) {
                    FileEntity file = fileManager.getFileByUuid(fileUuid);
                    if (file == null) {
                        String errMsg = "Can't find file from repository with id=" + fileUuid;
                        LOG.error(errMsg);
                        throw new Exception("Internal error - " + errMsg);
                    }
                    deliverableManager.addFile(entity, file);
                }
                if (partName.equals("removeFile")) {
                    Iterator<FileEntity> itr = entity.getFiles().iterator();
                    while (itr.hasNext()) {
                        FileEntity file = itr.next();
                        if (file.getUuid().equals(fileUuid)) {
                            itr.remove();
                        }
                    }
                    FileEntity file = fileManager.getFileByUuid(fileUuid);
                    fileManager.deleteFile(file);

                }
            }

            entity = deliverableManager.regenerateImageContent(entity);
            deliverableManager.saveDeliverable(deliveryPipeId, entity);
            response.setData(((CustomContentEntity) entity.getContent()).getContent());

        } catch (Exception ex) {
            LOG.error(ex);
            response.setMessage("File handling failed");
            response.setError(ex.getLocalizedMessage());
            return new ResponseEntity<>(response, HttpStatus.INTERNAL_SERVER_ERROR);
        }

        LOG.info("File handling completed");
        response.setMessage("File(s) handled");
        response.setError("");
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    // File removing without automatic content regeneration
    @PreAuthorize("hasAnyAuthority('ADMIN','PROVIDER')")
    @RequestMapping(value = {"/fileremovebyuuid/{fileUuid}"})
    public @ResponseBody
    ResponseEntity<String> removeFileByUuid(
            @PathVariable("fileUuid") String fileUuid,
            MultipartHttpServletRequest request
    ) {
        LOG.info("Removing file by UUID=" + fileUuid);

        FileEntity fileToRemove = fileManager.getFileByUuid(fileUuid);
        if (fileToRemove != null) {
            deliverableManager.removeFileFromDeliverables(fileToRemove);
        }

        LOG.info("Removing completed");
        return new ResponseEntity<>("Request completed", HttpStatus.OK);
    }

//</editor-fold>

}
