package com.mnewservice.mcontent.repository.entity;

import javax.persistence.*;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
@Entity
@Table(name = "deliverables")
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(name = "deliverableType", discriminatorType = DiscriminatorType.STRING)
public abstract class AbstractDeliverableEntity extends AbstractEntity {

    public enum DeliverableStatusEnum {

        PENDING_APPROVAL,
        APPROVED
    }

    @ManyToOne
    @JoinColumn(updatable = false)
    private DeliveryPipeEntity deliveryPipe;

    @OneToOne(cascade = CascadeType.ALL)
    private AbstractContentEntity content;

    @Enumerated(EnumType.STRING)
    private DeliverableStatusEnum status;

//<editor-fold desc="autogenerated getter/setter region">
    public DeliveryPipeEntity getDeliveryPipe() {
        return deliveryPipe;
    }

    public void setDeliveryPipe(DeliveryPipeEntity deliveryPipe) {
        this.deliveryPipe = deliveryPipe;
    }

    public AbstractContentEntity getContent() {
        return content;
    }

    public void setContent(AbstractContentEntity content) {
        this.content = content;
    }

    public DeliverableStatusEnum getStatus() {
        return status;
    }

    public void setStatus(DeliverableStatusEnum status) {
        this.status = status;
    }
    //</editor-fold>

}
