package com.mnewservice.mcontent.repository.entity;

import java.util.List;
import javax.persistence.*;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
@Entity
@Table(name = "deliverables")
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(name = "deliverableType", discriminatorType = DiscriminatorType.STRING)
public abstract class AbstractDeliverableEntity extends AbstractEntity {

    public enum DeliverableStatusEnum {

        DRAFT,
        PENDING_APPROVAL,
        APPROVED,
        DISAPPROVED
    }

    @ManyToOne
    @JoinColumn(updatable = false)
    private DeliveryPipeEntity deliveryPipe;

    @OneToOne(cascade = CascadeType.ALL)
    private AbstractContentEntity content;

    @Enumerated(EnumType.STRING)
    private DeliverableStatusEnum status;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    private List<FileEntity> files;

//<editor-fold desc="autogenerated getter/setter region">
    public DeliveryPipeEntity getDeliveryPipe() {
        return deliveryPipe;
    }

    public void setDeliveryPipe(DeliveryPipeEntity deliveryPipe) {
        this.deliveryPipe = deliveryPipe;
    }

    public AbstractContentEntity getContent() {
        return content;
    }

    public void setContent(AbstractContentEntity content) {
        this.content = content;
    }

    public DeliverableStatusEnum getStatus() {
        return status;
    }

    public void setStatus(DeliverableStatusEnum status) {
        this.status = status;
    }

    public List<FileEntity> getFiles() {
        return files;
    }

    public void setFiles(List<FileEntity> files) {
        this.files = files;
    }

//</editor-fold>
}
