package com.mnewservice.mcontent.repository.entity;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
@Entity
@Table(name = "phonenumbers")
public class PhoneNumberEntity extends AbstractEntity {

    private String number;

    // <editor-fold defaultstate="collapsed" desc="autogenerated getters / setters">
    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }
    // </editor-fold>

}
