package com.mnewservice.mcontent.repository.entity;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Table;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
@Entity
@Table(name = "roles")
public class RoleEntity extends AbstractEntity {

    public static enum RoleEnum {

        ADMIN,
        PROVIDER
    }

    @Enumerated(EnumType.STRING)
    private RoleEnum name;

    // <editor-fold defaultstate="collapsed" desc="autogenerated getters / setters">
    public RoleEnum getName() {
        return name;
    }

    public void setName(RoleEnum name) {
        this.name = name;
    }
// </editor-fold>
}
