package com.mnewservice.mcontent.repository.entity;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
@Entity
@Table(name = "roles")
public class RoleEntity extends AbstractEntity {

    @Version
    private Long version;

    private String roleName;

    // <editor-fold defaultstate="collapsed" desc="autogenerated getters / setters">
    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
// </editor-fold>
}
