package com.mnewservice.mcontent.repository.entity;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
@Entity
@Table(
        name = "services",
        uniqueConstraints = @UniqueConstraint(
                columnNames = {"keyword", "shortCode", "operator"}
        )
)
public class ServiceEntity extends AbstractEntity {

    public static enum DeliveryTime {

        T0800,
        T1000,
        T1200,
        T1400,
        T1600,
        T1800,
        T2000,
        T2200
    }

    private String keyword;
    private int shortCode;
    private String operator;
    @ManyToOne
    private UserEntity provider;
    private int subscriptionPeriod;

    @Enumerated(EnumType.STRING)
    private DeliveryTime deliveryTime;

    // <editor-fold defaultstate="collapsed" desc="autogenerated getters / setters">
    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public Integer getShortCode() {
        return shortCode;
    }

    public void setShortCode(Integer shortCode) {
        this.shortCode = shortCode;
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public UserEntity getProvider() {
        return provider;
    }

    public void setProvider(UserEntity provider) {
        this.provider = provider;
    }

    public int getSubscriptionPeriod() {
        return subscriptionPeriod;
    }

    public void setSubscriptionPeriod(int subscriptionPeriod) {
        this.subscriptionPeriod = subscriptionPeriod;
    }

    public DeliveryTime getDeliveryTime() {
        return deliveryTime;
    }

    public void setDeliveryTime(DeliveryTime deliveryTime) {
        this.deliveryTime = deliveryTime;
    }
// </editor-fold>
}
