package com.mnewservice.mcontent.repository.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
@Entity
@Table(
        name = "services",
        uniqueConstraints = {
            @UniqueConstraint(
                    columnNames = {"keyword", "shortCode", "operator"}
            ),
            @UniqueConstraint(
                    columnNames = {"unsubscribeKeyword", "shortCode", "operator"}
            )
        }
)
public class ServiceEntity extends AbstractEntity {

    public static enum DeliveryTime {

        T0800,
        T1000,
        T1200,
        T1400,
        T1600,
        T1800,
        T2000,
        T2200
    }

    @Column(length = 160)
    private String keyword;

    private int shortCode;

    private String operator;

    @Column(length = 160)
    private String unsubscribeKeyword;

    private int subscriptionPeriod;

    @Column(length = 160)
    private String welcomeMessage;

    @Column(length = 160)
    private String renewMessage;

    @Column(length = 160)
    private String expireMessage;

    @Column(length = 160)
    private String unsubscribeMessage;

    @ManyToOne
    private DeliveryPipeEntity deliveryPipe;

    @Enumerated(EnumType.STRING)
    private DeliveryTime deliveryTime;

    // <editor-fold defaultstate="collapsed" desc="autogenerated getters / setters">
    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getUnsubscribeKeyword() {
        return unsubscribeKeyword;
    }

    public void setUnsubscribeKeyword(String unsubscribeKeyword) {
        this.unsubscribeKeyword = unsubscribeKeyword;
    }

    public Integer getShortCode() {
        return shortCode;
    }

    public void setShortCode(Integer shortCode) {
        this.shortCode = shortCode;
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public int getSubscriptionPeriod() {
        return subscriptionPeriod;
    }

    public void setSubscriptionPeriod(int subscriptionPeriod) {
        this.subscriptionPeriod = subscriptionPeriod;
    }

    public String getWelcomeMessage() {
        return welcomeMessage;
    }

    public void setWelcomeMessage(String welcomeMessage) {
        this.welcomeMessage = welcomeMessage;
    }

    public String getRenewMessage() {
        return renewMessage;
    }

    public void setRenewMessage(String renewMessage) {
        this.renewMessage = renewMessage;
    }

    public String getExpireMessage() {
        return expireMessage;
    }

    public void setExpireMessage(String expireMessage) {
        this.expireMessage = expireMessage;
    }

    public String getUnsubscribeMessage() {
        return unsubscribeMessage;
    }

    public void setUnsubscribeMessage(String unsubscribeMessage) {
        this.unsubscribeMessage = unsubscribeMessage;
    }

    public DeliveryPipeEntity getDeliveryPipe() {
        return deliveryPipe;
    }

    public void setDeliveryPipe(DeliveryPipeEntity deliveryPipe) {
        this.deliveryPipe = deliveryPipe;
    }

    public DeliveryTime getDeliveryTime() {
        return deliveryTime;
    }

    public void setDeliveryTime(DeliveryTime deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

// </editor-fold>
}
