package com.mnewservice.mcontent.domain;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
public class Email {

    private String address;

    // <editor-fold defaultstate="collapsed" desc="autogenerated getters / setters">
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    // </editor-fold>
}
