package com.mnewservice.mcontent.domain;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
public class PhoneNumber {

    private String number;

    // <editor-fold defaultstate="collapsed" desc="autogenerated getters / setters">
    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }
    // </editor-fold>

}
