package com.mnewservice.mcontent.domain;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
public class Service {

    private Long id;

    private String keyword;
    private int shortCode;
    private String operator;
    private String unsubscribeKeyword;
    private int subscriptionPeriod;
    private DeliveryPipe deliveryPipe;
    private DeliveryTime deliveryTime;

    // <editor-fold defaultstate="collapsed" desc="autogenerated getters / setters">
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public int getShortCode() {
        return shortCode;
    }

    public void setShortCode(int shortCode) {
        this.shortCode = shortCode;
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public String getUnsubscribeKeyword() {
        return unsubscribeKeyword;
    }

    public void setUnsubscribeKeyword(String unsubscribeKeyword) {
        this.unsubscribeKeyword = unsubscribeKeyword;
    }

    public int getSubscriptionPeriod() {
        return subscriptionPeriod;
    }

    public void setSubscriptionPeriod(int subscriptionPeriod) {
        this.subscriptionPeriod = subscriptionPeriod;
    }

    public DeliveryPipe getDeliveryPipe() {
        return deliveryPipe;
    }

    public void setDeliveryPipe(DeliveryPipe deliveryPipe) {
        this.deliveryPipe = deliveryPipe;
    }

    public DeliveryTime getDeliveryTime() {
        return deliveryTime;
    }

    public void setDeliveryTime(DeliveryTime deliveryTime) {
        this.deliveryTime = deliveryTime;
    }
    // </editor-fold>

}
