package com.mnewservice.mcontent.domain;

import java.util.Collection;

/**
 *
 * @author Marko Tuononen <marko.tuononen at nolwenture.com>
 */
public class Subscription {

    private Long id;
    private Service service;
    private PhoneNumber subscriber;
    private Collection<SubscriptionPeriod> periods;

    // <editor-fold defaultstate="collapsed" desc="autogenerated getters / setters">
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Service getService() {
        return service;
    }

    public void setService(Service service) {
        this.service = service;
    }

    public PhoneNumber getSubscriber() {
        return subscriber;
    }

    public void setSubscriber(PhoneNumber subscriber) {
        this.subscriber = subscriber;
    }

    public Collection<SubscriptionPeriod> getPeriods() {
        return periods;
    }

    public void setPeriods(Collection<SubscriptionPeriod> periods) {
        this.periods = periods;
    }
    // </editor-fold>
}
